name: 電気料金通知

on:
  schedule:
    - cron: '0 20 * * *'  # 毎日午後8時に実行
  workflow_dispatch:      # 手動実行用

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth dotenv @line/bot-sdk cheerio

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Create env file
        run: |
          echo "TEPCO_USERNAME=${{ secrets.TEPCO_USERNAME }}" >> .env
          echo "TEPCO_PASSWORD=${{ secrets.TEPCO_PASSWORD }}" >> .env
          echo "LINE_CHANNEL_TOKEN=${{ secrets.LINE_CHANNEL_TOKEN }}" >> .env
          echo "LINE_USER_ID=${{ secrets.LINE_USER_ID }}" >> .env

      - name: Run script with Xvfb
        run: xvfb-run --auto-servernum node main.js 