name: 電気料金通知

on:
  schedule:
    - cron: '0 11 * * *'  # 毎日20:00 JST (11:00 UTC)
  workflow_dispatch:      # 手動実行用

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/takuoka/AutoReporter.git .
          git checkout ${{ github.sha }}

      - name: Setup Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth dotenv @line/bot-sdk cheerio

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Create env file
        run: |
          echo "TEPCO_USERNAME=${{ secrets.TEPCO_USERNAME }}" >> .env
          echo "TEPCO_PASSWORD=${{ secrets.TEPCO_PASSWORD }}" >> .env
          echo "LINE_CHANNEL_TOKEN=${{ secrets.LINE_CHANNEL_TOKEN }}" >> .env
          echo "LINE_USER_ID=${{ secrets.LINE_USER_ID }}" >> .env

      - name: Run script with Xvfb
        run: xvfb-run --auto-servernum node main.js 